name: Coverage
on: [push]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: dependencies
        run: npm install

      - name: test
        run: npm run test -- --coverage
        run: bash <(curl -s https://codecov.io/bash) -f ./coverage/coverage-final.json
