name: Quality checks

on: [push]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0 # Required to retrieve git history for Chromatic

      - name: Install dependencies
        run: npm install

      - name: Run eslint
        run: npm run lint

      - name: Run TypeScript
        run: npm run types

      - name: Run Tests
        run: |
          npm run test -- --coverage
          bash <(curl -s https://codecov.io/bash) -f ./coverage/coverage-final.json

      - name: Upload to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
