name: Quality checks
on: [push]
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: dependencies
        run: npm install

      - name: lint
        run: npm run lint

      - name: types
        run: npm run types

      - name: test
        run: npm run test -- --coverage
        run: bash <(curl -s https://codecov.io/bash) -f ./coverage/coverage-final.json

      - name: Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: "pq9dwlqeah"
